// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://istwpxixdguainwazjak.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdHdweGl4ZGd1YWlud2F6amFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzODM5NTMsImV4cCI6MjA0Nzk1OTk1M30.UPyiVaZVyAIZJMxlN3SoKcOumJ5rZUwB46fp5l6FfOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);